export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  GET_ALL_USERS_REQUEST: " GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: " GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: " GET_ALL_USERS_FAILURE",

  GET_USER_DETAIL_BY_ID_REQUEST: " GET_USER_DETAIL_BY_ID_REQUEST",
  GET_USER_DETAIL_BY_ID_SUCCESS: " GET_USER_DETAIL_BY_ID_SUCCESS",
  GET_USER_DETAIL_BY_ID_FAILURE: " GET_USER_DETAIL_BY_ID_FAILURE",
};

export const enterpriseConstants = {
  GET_ALL_ENTERPRISES_REQUEST: " GET_ALL_ENTERPRISES_REQUEST",
  GET_ALL_ENTERPRISES_SUCCESS: " GET_ALL_ENTERPRISES_SUCCESS",
  GET_ALL_ENTERPRISES_FAILURE: " GET_ALL_ENTERPRISES_FAILURE",

  ADD_NEW_ENTERPRISES_REQUEST: "ADD_NEW_ENTERPRISES_REQUEST",
  ADD_NEW_ENTERPRISES_SUCCESS: "ADD_NEW_ENTERPRISES_SUCCESS",
  ADD_NEW_ENTERPRISES_FAILURE: "ADD_NEW_ENTERPRISES_FAILURE",

  EDIT_ENTERPRIESE_REQUEST: "EDIT_ENTERPRIESE_REQUEST",
  EDIT_ENTERPRIESE_SUCCESS: "EDIT_ENTERPRIESE_SUCCESS",
  EDIT_ENTERPRIESE_FAILURE: "EDIT_ENTERPRIESE_FAILURE",

  DELETE_ENTERPRIESE_REQUEST: "DELETE_ENTERPRIESE_REQUEST",
  DELETE_ENTERPRIESE_SUCCESS: "DELETE_ENTERPRIESE_SUCCESS",
  DELETE_ENTERPRIESE_FAILURE: "DELETE_ENTERPRIESE_FAILURE",

  GET_ENTERPRISES_DETAILS_BY_ID_REQUEST:
    "GET_ENTERPRISES_DETAILS_BY_ID_REQUEST",
  GET_ENTERPRISES_DETAILS_BY_ID_SUCCESS:
    "GET_ENTERPRISES_DETAILS_BY_ID_SUCCESS",
  GET_ENTERPRISES_DETAILS_BY_ID_FAILURE:
    "GET_ENTERPRISES_DETAILS_BY_ID_FAILURE",
};

export const routerConstants = {
  GET_ALL_ROUTES_REQUEST: " GET_ALL_ROUTES_REQUEST",
  GET_ALL_ROUTES_SUCCESS: " GET_ALL_ROUTES_SUCCESS",
  GET_ALL_ROUTES_FAILURE: " GET_ALL_ROUTES_FAILURE",

  ADD_NEW_ROUTE_REQUEST: "ADD_NEW_ROUTE_REQUEST",
  ADD_NEW_ROUTE_SUCCESS: "ADD_NEW_ROUTE_SUCCESS",
  ADD_NEW_ROUTE_FAILURE: "ADD_NEW_ROUTE_FAILURE",

  EDIT_ROUTE_REQUEST: "EDIT_ROUTE_REQUEST",
  EDIT_ROUTE_SUCCESS: "EDIT_ROUTE_SUCCESS",
  EDIT_ROUTE_FAILURE: "EDIT_ROUTE_FAILURE",

  DELETE_ROUTE_REQUEST: "DELETE_ROUTE_REQUEST",
  DELETE_ROUTE_SUCCESS: "DELETE_ROUTE_SUCCESS",
  DELETE_ROUTE_FAILURE: "DELETE_ROUTE_FAILURE",

  GET_ROUTES_DETAILS_BY_ID_REQUEST: "GET_ROUTES_DETAILS_BY_ID_REQUEST",
  GET_ROUTES_DETAILS_BY_ID_SUCCESS: "GET_ROUTES_DETAILS_BY_ID_SUCCESS",
  GET_ROUTES_DETAILS_BY_ID_FAILURE: "GET_ROUTES_DETAILS_BY_ID_FAILURE",
};

export const cityConstants = {
  GET_ALL_CITIES_REQUEST: " GET_ALL_CITIES_REQUEST",
  GET_ALL_CITIES_SUCCESS: " GET_ALL_CITIES_SUCCESS",
  GET_ALL_CITIES_FAILURE: " GET_ALL_CITIES_FAILURE",
};

export const vehicleConstants = {
  GET_ALL_VEHICLES_REQUEST: " GET_ALL_VEHICLES_REQUEST",
  GET_ALL_VEHICLES_SUCCESS: " GET_ALL_VEHICLES_SUCCESS",
  GET_ALL_VEHICLES_FAILURE: " GET_ALL_VEHICLES_FAILURE",

  ADD_NEW_VEHICLE_REQUEST: "ADD_NEW_VEHICLE_REQUEST",
  ADD_NEW_VEHICLE_SUCCESS: "ADD_NEW_VEHICLE_SUCCESS",
  ADD_NEW_VEHICLE_FAILURE: "ADD_NEW_VEHICLE_FAILURE",

  EDIT_VEHICLE_REQUEST: "EDIT_VEHICLE_REQUEST",
  EDIT_VEHICLE_SUCCESS: "EDIT_VEHICLE_SUCCESS",
  EDIT_VEHICLE_FAILURE: "EDIT_VEHICLE_FAILURE",

  DELETE_VEHICLE_REQUEST: "DELETE_VEHICLE_REQUEST",
  DELETE_VEHICLE_SUCCESS: "DELETE_VEHICLE_SUCCESS",
  DELETE_VEHICLE_FAILURE: "DELETE_VEHICLE_FAILURE",
};

export const tripConstants = {
  GET_ALL_TRIP_REQUEST: "GET_ALL_TRIP_REQUEST",
  GET_ALL_TRIP_SUCCESS: "GET_ALL_TRIP_SUCCESS",
  GET_ALL_TRIP_FAILURE: "GET_ALL_TRIP_FAILURE",

  ADD_NEW_TRIP_REQUEST: "ADD_NEW_TRIP_REQUEST",
  ADD_NEW_TRIP_SUCCESS: "ADD_NEW_TRIP_SUCCESS",
  ADD_NEW_TRIP_FAILURE: "ADD_NEW_TRIP_FAILURE",

  EDIT_TRIP_REQUEST: "EDIT_TRIP_REQUEST",
  EDIT_TRIP_SUCCESS: "EDIT_TRIP_SUCCESS",
  EDIT_TRIP_FAILURE: "EDIT_TRIP_FAILURE",

  GET_TRIP_DETAILS_BY_ID_REQUEST: "GET_TRIP_DETAILS_BY_ID_REQUEST",
  GET_TRIP_DETAILS_BY_ID_SUCCESS: "GET_TRIP_DETAILS_BY_ID_SUCCESS",
  GET_TRIP_DETAILS_BY_ID_FAILURE: "GET_TRIP_DETAILS_BY_ID_FAILURE",

  GET_TRIP_DETAILS_BY_ID_LOCATION_REQUEST:
    "GET_TRIP_DETAILS_BY_ID_LOCATION_REQUEST",
  GET_TRIP_DETAILS_BY_ID_LOCATION_SUCCESS:
    "GET_TRIP_DETAILS_BY_ID_LOCATION_SUCCESS",
  GET_TRIP_DETAILS_BY_ID_LOCATION_FAILURE:
    "GET_TRIP_DETAILS_BY_ID_LOCATION_FAILURE",

  TRIP_FETCH: "TRIP_FETCH",
  TRIP_CREATE: "TRIP_CREATE",
  TRIP_GET_ALL: "TRIP_GET_ALL",
  TRIP_GET_BY_ID: "TRIP_GET_BY_ID",
};

export const steersmanConstants = {
  GET_ALL_STEERSMAN_REQUEST: " GET_ALL_STEERSMAN_REQUEST",
  GET_ALL_STEERSMAN_SUCCESS: " GET_ALL_STEERSMAN_SUCCESS",
  GET_ALL_STEERSMAN_FAILURE: " GET_ALL_STEERSMAN_FAILURE",

  ADD_NEW_STEERSMAN_REQUEST: "ADD_NEW_STEERSMAN_REQUEST",
  ADD_NEW_STEERSMAN_SUCCESS: "ADD_NEW_STEERSMAN_SUCCESS",
  ADD_NEW_STEERSMAN_FAILURE: "ADD_NEW_STEERSMAN_FAILURE",

  EDIT_STEERSMAN_REQUEST: "EDIT_STEERSMAN_REQUEST",
  EDIT_STEERSMAN_SUCCESS: "EDIT_STEERSMAN_SUCCESS",
  EDIT_STEERSMAN_FAILURE: "EDIT_STEERSMAN_FAILURE",

  DELETE_STEERSMAN_REQUEST: "DELETE_STEERSMAN_REQUEST",
  DELETE_STEERSMAN_SUCCESS: "DELETE_STEERSMAN_SUCCESS",
  DELETE_STEERSMAN_FAILURE: "DELETE_STEERSMAN_FAILURE",
};

export const ticketConstants = {
  GET_ALL_TICKETS_REQUEST: " GET_ALL_TICKETS_REQUEST",
  GET_ALL_TICKETS_SUCCESS: " GET_ALL_TICKETS_SUCCESS",
  GET_ALL_TICKETS_FAILURE: " GET_ALL_TICKETS_FAILURE",

  ADD_NEW_TICKET_REQUEST: "ADD_NEW_TICKET_REQUEST",
  ADD_NEW_TICKET_SUCCESS: "ADD_NEW_TICKET_SUCCESS",
  ADD_NEW_TICKET_FAILURE: "ADD_NEW_TICKET_FAILURE",

  ADD_NEW_OFFLINETICKET_REQUEST: "ADD_NEW_OFFLINETICKET_REQUEST",
  ADD_NEW_OFFLINETICKET_SUCCESS: "ADD_NEW_OFFLINETICKET_SUCCESS",
  ADD_NEW_OFFLINETICKET_FAILURE: "ADD_NEW_OFFLINETICKET_FAILURE",

  GET_ALL_OFFLINETICKETS_REQUEST: " GET_ALL_OFFLINETICKETS_REQUEST",
  GET_ALL_OFFLINETICKETS_SUCCESS: " GET_ALL_OFFLINETICKETS_SUCCESS",
  GET_ALL_OFFLINETICKETS_FAILURE: " GET_ALL_OFFLINETICKETS_FAILURE",
};

export const analyticsConstants = {
  ANALYTICS_REQUEST: "ANALYTICS_REQUEST",
  ANALYTICS_SUCCESS: "ANALYTICS_SUCCESS",
  ANALYTICS_FAILURE: "ANALYTICS_FAILURE",

  ANALYTICS_CHART_REQUEST: "ANALYTICS_CHART_REQUEST",
  ANALYTICS_CHART_SUCCESS: "ANALYTICS_CHART_SUCCESS",
  ANALYTICS_CHART_FAILURE: "ANALYTICS_CHART_FAILURE",

  NEW_USER_REQUEST: "NEW_USER_REQUEST",
  NEW_USER_SUCCESS: "NEW_USER_SUCCESS",
  NEW_USER_FAILURE: "NEW_USER_FAILURE",

  TICKET_DONUT_REQUEST: "TICKET_DONUT_REQUEST",
  TICKET_DONUT_SUCCESS: "TICKET_DONUT_SUCCESS",
  TICKET_DONUT_FAILURE: "TICKET_DONUT_FAILURE",

  CURRENT_DATE_REQUEST: "CURRENT_DATE_REQUEST",
  CURRENT_DATE_SUCCESS: "CURRENT_DATE_SUCCESS",
  CURRENT_DATE_FAILURE: "CURRENT_DATE_FAILURE",

  CHART_ENTERPRISE_REQUEST: "CHART_ENTERPRISE_REQUEST",
  CHART_ENTERPRISE_SUCCESS: "CHART_ENTERPRISE_SUCCESS",
  CHART_ENTERPRISE_FAILURE: "CHART_ENTERPRISE_FAILURE",

  LIST_ENTERPRISE_REQUEST: "LIST_ENTERPRISE_REQUEST",
  LIST_ENTERPRISE_SUCCESS: "LIST_ENTERPRISE_SUCCESS",
  LIST_ENTERPRISE_FAILURE: "LIST_ENTERPRISE_FAILURE",

  NAME_CHART_ENTERPRISE_REQUEST: "NAME_CHART_ENTERPRISE_REQUEST",
  NAME_CHART_ENTERPRISE_SUCCESS: "NAME_CHART_ENTERPRISE_SUCCESS",
  NAME_CHART_ENTERPRISE_FAILURE: "NAME_CHART_ENTERPRISE_FAILURE",

  LAST_ORDER_REQUEST: "LAST_ORDER_REQUEST",
  LAST_ORDER_SUCCESS: "LAST_ORDER_SUCCESS",
  LAST_ORDER_FAILURE: "LAST_ORDER_FAILURE",
};

export const userTicketConstants = {
  BOOK_SUCCESS: "BOOK_SUCCESS",
  BOOK_FAILURE: "BOOK_FAILURE",
  BOOK_GET_ALL: "BOOK_GET_ALL",
};

export const wagonTicketConstants = {
  ADD_NEW_WAGON_TICKET_REQUEST: "ADD_NEW_WAGON_TICKET_REQUEST",
  ADD_NEW_WAGON_TICKET_SUCCESS: "ADD_NEW_WAGON_TICKET_SUCCESS",
  ADD_NEW_WAGON_TICKET_FAILURE: "ADD_NEW_WAGON_TICKET_FAILURE",

  EDIT_WAGON_TICKET_REQUEST: "EDIT_WAGON_TICKET_REQUEST",
  EDIT_WAGON_TICKET_SUCCESS: "EDIT_WAGON_TICKET_SUCCESS",
  EDIT_WAGON_TICKET_FAILURE: "EDIT_WAGON_TICKET_FAILURE",
};
